name: Publish to PyPI and TestPyPI

on: [push, release]

jobs:
  build-n-publish:
    name: Build and publish to PyPI and TestPyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master

      - name: Set up Python
        uses: actions/setup-python@v1
        with:
          python-version: 3.9

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install wheel

      - name: Build distributions via setup.py
        run: >-
          python setup.py
          sdist --formats=zip
          bdist_wheel

      - name: Publish to TestPyPI
        if: ${{ github.event_name == 'release' && github.event.action == 'prerelease' }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.TEST_PYPI_API_TOKEN }}
          repository_url: https://test.pypi.org/legacy/

      - name: Publish to PyPI
        if: ${{ github.event_name == 'release' && github.event.action == 'release' }}
        uses: pypa/gh-action-pypi-publish@master
        with:
          password: ${{ secrets.PYPI_API_TOKEN }}

      - name: Debug
        run: |
          echo "event_name ${{ github.event_name }}"
          echo "event.action ${{ github.event.action }}"
